// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNvmpyAovx_4kE-UYlpFmJgBiFR4pkVqU',
    appId: '1:49794661773:android:aa90f5ccaa203798c6d1c4',
    messagingSenderId: '49794661773',
    projectId: 'resortconnect-f7dd6',
    databaseURL: 'https://resortconnect-f7dd6-default-rtdb.firebaseio.com',
    storageBucket: 'resortconnect-f7dd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJTe5W8U6R2goncA23I7PINPBOe7z02Zw',
    appId: '1:49794661773:ios:7e8bf51974fbe797c6d1c4',
    messagingSenderId: '49794661773',
    projectId: 'resortconnect-f7dd6',
    databaseURL: 'https://resortconnect-f7dd6-default-rtdb.firebaseio.com',
    storageBucket: 'resortconnect-f7dd6.firebasestorage.app',
    iosBundleId: 'com.example.resortconnectapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8favTsJbL6Kcr5-oaoovV3OUya4bnRU4',
    appId: '1:49794661773:web:8d67cdad5d6b45a2c6d1c4',
    messagingSenderId: '49794661773',
    projectId: 'resortconnect-f7dd6',
    authDomain: 'resortconnect-f7dd6.firebaseapp.com',
    databaseURL: 'https://resortconnect-f7dd6-default-rtdb.firebaseio.com',
    storageBucket: 'resortconnect-f7dd6.firebasestorage.app',
    measurementId: 'G-7PJXLQH6RL',
  );

}